'use strict';
const fs=require('fs'),vm=require('vm'),path=require('path');
const assert=(c,m)=>{if(!c)throw new Error('FALHOU: '+m)};
const source=fs.readFileSync(path.resolve(__dirname,'../js/24-interconnections.js'),'utf8');
const context={console,crypto:global.crypto,setTimeout,clearTimeout,setInterval,clearInterval,structuredClone:global.structuredClone};
context.window=context;context.globalThis=context;context.addEventListener=()=>{};
context.document={addEventListener(){},querySelectorAll(){return[]},querySelector(){return null},getElementById(){return null},hidden:false};
context.CARTEIRA_CONTA_ID='wallet';context.FORMAS_PAGAMENTO=['Dinheiro','Pix','Débito','Crédito'];context.defaultCategories=()=>({receita:[],fixa:[],variavel:[]});context.baseCatColor=()=> '#888';context.todayISO=()=> '2026-07-21';
context.S={profiles:[],currentProfile:null,data:null};context.getProfileData=()=>null;context.setProfileData=()=>{};context.migrateData=v=>v;context.emptyData=()=>({});context.toast=()=>{};context.alert=()=>{};
vm.createContext(context);vm.runInContext(source,context,{filename:'24-interconnections.js'});
const methods=['pix','money','debit',...Array.from({length:12},(_,i)=>'credit'+(i+1))];
const rules=Object.fromEntries(methods.map(key=>[key,{category:'Receitas MIT',destinationKind:key==='money'?'wallet':'account',accountId:key==='money'?'wallet':'bank1',reserveId:null,target:key==='money'?'wallet':'account:bank1'}]));
const makeData=()=>({transacoes:[{id:'tx-imported',integrationSourceAppId:'marco-iris',integrationReceiptId:'REC-OLD',integrationAggregateId:'old-agg'}],contas:[{id:'wallet',nome:'Carteira',isCarteira:true},{id:'bank1',nome:'Banco'}],liquidez:[],categorias:{receita:['Receitas MIT'],fixa:[],variavel:[]},categoryColors:{receita:{},fixa:{},variavel:{}},modules:{},reservas:{boxes:[],moves:[]},interconnections:{sources:{},imported:{},ignored:{},pending:[],audit:[],mitImported:{receipts:{},expenses:{}}}});
const config={sourceAppId:'marco-iris',enabled:true,mappingReady:true,mitRevenueRules:rules,accountId:'bank1',mitExpenseRules:{},mitExpenseMappingReady:false,importCutoffAt:''};
const cancelled=(id,aggregate)=>({aggregateId:aggregate,sourceRecordId:'marco:receipt:'+id,entityId:id,receiptId:id,direction:'income',amount:100,date:'2026-07-20',paymentDate:'2026-07-20',status:'cancelled',active:false,settled:false,operationType:'cancel',sourceUpdatedAt:'2026-07-21T01:00:00Z'});
const snapshot={schema:'borion.interop.snapshot',schemaVersion:2,sourceAppId:'marco-iris',companyInstanceId:'company-ok',deviceId:'device-a',revision:5,recordCount:2,isCompleteSnapshot:true,records:[cancelled('REC-OLD','marco-iris:company-ok:receipt:REC-OLD'),cancelled('REC-NEW','marco-iris:company-ok:receipt:REC-NEW')],tombstones:[]};
const data=makeData();data.interconnections.sources['marco-iris']=config;
const result=context.BorionInterop.__test.reconcileMitSnapshot(data,config,snapshot,{mode:'automatic'});
assert(result.results.find(x=>x.entityId==='REC-OLD').result==='cancelled','receita importada e cancelada deve retornar cancelled');
assert(result.results.find(x=>x.entityId==='REC-OLD').borionTransactionId==='tx-imported','vínculo importado deve ser preservado');
assert(data.transacoes.some(x=>x.id==='tx-imported'),'cancelamento não pode apagar silenciosamente o lançamento já importado');
assert(result.results.find(x=>x.entityId==='REC-NEW').result==='cancelled','receita não importada e cancelada deve ser encerrada');
assert(data.transacoes.length===1,'receita cancelada sem importação não pode criar lançamento');
console.log('OK: cancelamento de receita preserva lançamento importado, encerra não importado e retorna ACK cancelled.');
