'use strict';
const fs=require('fs'),vm=require('vm'),path=require('path');
const assert=(c,m)=>{if(!c)throw new Error('FALHOU: '+m)};
const source=fs.readFileSync(path.resolve(__dirname,'../js/24-interconnections.js'),'utf8');
const context={console,crypto:global.crypto,setTimeout,clearTimeout,setInterval,clearInterval,structuredClone:global.structuredClone};
context.window=context;context.globalThis=context;context.addEventListener=()=>{};
context.document={addEventListener(){},querySelectorAll(){return[]},querySelector(){return null},getElementById(){return null},hidden:false};
context.CARTEIRA_CONTA_ID='wallet';context.FORMAS_PAGAMENTO=['Dinheiro','Pix','Débito','Crédito'];context.defaultCategories=()=>({receita:[],fixa:[],variavel:[]});context.baseCatColor=()=> '#888';context.todayISO=()=> '2026-07-21';
context.S={profiles:[],currentProfile:null,data:null};context.getProfileData=()=>null;context.setProfileData=()=>{};context.migrateData=v=>v;context.emptyData=()=>({});context.toast=()=>{};context.alert=()=>{};
vm.createContext(context);vm.runInContext(source,context,{filename:'24-interconnections.js'});
const config={sourceAppId:'marco-iris',enabled:true,mappingReady:true,companyInstanceId:'old-install',accountId:'bank1',importCutoffAt:'2026-07-21',mitRevenueRules:{pix:{category:'Receitas MIT',destinationKind:'account',accountId:'bank1'}}};
const nativeTx={id:'old-native',tipo:'receita',nome:'Já importado',valor:10,integrationSourceAppId:'marco-iris',integrationAggregateId:'marco-iris:old-install:receipt:r1'};
const data={transacoes:[nativeTx],contas:[{id:'bank1',nome:'Banco'}],categorias:{receita:['Receitas MIT'],fixa:[],variavel:[]},categoryColors:{receita:{},fixa:{},variavel:{}},reservas:{boxes:[],moves:[]},interconnections:{sources:{'marco-iris':config},imported:{'marco-iris':{companyInstanceId:'old-install',instanceId:'old-install',lastRevision:99,lastContentHash:'abc',records:{old:{status:'imported',txId:'old-native'}}}},ignored:{'marco-iris':{old:{ignoredAt:'x'}}},pending:[{sourceAppId:'marco-iris',aggregateId:'old-pending'}],audit:[],mitImported:{receipts:{r1:{borionId:'old-native'}},expenses:{e1:{borionId:'x'}}}}};
const snapshot={schema:'borion.interop.snapshot',schemaVersion:2,sourceAppId:'marco-iris',companyInstanceId:'new-install',deviceId:'device-new',revision:1,recordCount:1,isCompleteSnapshot:true,records:[{sourceRecordId:'marco:receipt:new',aggregateId:'marco-iris:new-install:receipt:new',entityId:'new',direction:'income',active:true,status:'paid',settled:true,amount:1,date:'2026-07-21'}],tombstones:[]};
const result=context.BorionInterop.__test.applyConfirmedInstanceRebind(data,config,snapshot);
assert(result.previousCompanyInstanceId==='old-install'&&result.companyInstanceId==='new-install','deve trocar a instalação confirmada');
assert(data.transacoes.length===1&&data.transacoes[0].id==='old-native','lançamentos já existentes devem ser preservados');
assert(config.importCutoffAt==='2026-07-21'&&config.mappingReady===true,'data de corte e regras devem ser preservadas');
const state=data.interconnections.imported['marco-iris'];
assert(state.companyInstanceId==='new-install'&&state.lastRevision===0&&Object.keys(state.records).length===0,'estado técnico antigo deve ser zerado');
assert(data.interconnections.pending.length===0,'fila antiga deve ser removida');
assert(Object.keys(data.interconnections.ignored['marco-iris']).length===0,'ignorados antigos devem ser removidos');
assert(Object.keys(data.interconnections.mitImported.receipts).length===0&&Object.keys(data.interconnections.mitImported.expenses).length===0,'índices MIT antigos devem ser zerados');
assert(data.interconnections.instanceHistory[0].previousCompanyInstanceId==='old-install','troca deve ficar auditada');
console.log('OK: reconexão confirmada preserva lançamentos nativos e zera apenas vínculos técnicos da instalação antiga.');
