/* Teste automatizado sem dependências externas.
   Executar: node tests/test_importacao_prints_core.js */
const fs=require('fs');
const path=require('path');
const vm=require('vm');
const JS=path.join(__dirname,'..','js');
function createContext({failLast=false}={}){
  const context={console,window:{},document:{scripts:[],createElement(){return{}},head:{appendChild(){}},getElementById(){return null}},URL:{revokeObjectURL(){}},crypto:require('crypto').webcrypto,TextDecoder,FileReader:function(){},Image:function(){},createImageBitmap:undefined};context.window=context;
  const data={categorias:{receita:['Salário','Renda Extra','Reembolsos','Outro'],fixa:['Outro'],variavel:['Casa','Outro']},transacoes:[],fixas:[],transferencias:[],liquidez:[],contas:[{id:'mp',nome:'Mercado Pago',saldoInicial:0}],reservas:{enabled:true,boxes:[{id:'yas',nome:'Parcela YAS-62',accountId:'mp',banco:'Mercado Pago',valorAtual:0},{id:'pessoal',nome:'Pessoal',accountId:'mp',banco:'Mercado Pago',valorAtual:0},{id:'b1',nome:'Borion 1',accountId:'mp',banco:'Mercado Pago',valorAtual:100.05},{id:'b2',nome:'Borion 2',accountId:'mp',banco:'Mercado Pago',valorAtual:100.04}],moves:[]},modules:{reserves:true},importPreferences:{reserveMappings:{},merchantRules:{}},importBatches:[]};
  context.S={month:{y:2026,m:6},data,importState:null};let id=0,account=0,txCount=0;const toasts=[];
  const reserve=id=>context.S.data.reservas.boxes.find(b=>b.id===id);
  Object.assign(context,{pad2:n=>String(n).padStart(2,'0'),monthKey:(y,m)=>`${y}-${String(m+1).padStart(2,'0')}`,todayISO:()=> '2026-07-17',uid:()=>`id${++id}`,esc:s=>String(s),brl:n=>`R$ ${Number(n).toFixed(2)}`,renderView(){},toast(x){toasts.push(x)},openChoiceModal(){},closeModal(){},openModal(){},saveCurrentData(){},showBankRequiredModal(){},accountSelectOptions:()=>[{value:'mp',label:'Mercado Pago'}],resolveAccountId:x=>x==='mp'||x==='Mercado Pago'?'mp':'',accountNameSnapshot:x=>x==='mp'?'Mercado Pago':'',activeAccounts:()=>context.S.data.contas,boxAccountId:b=>b.accountId,applyTxSaldoEffect(tx){txCount++;if(failLast&&txCount===2)return false;account+=tx.tipo==='receita'?tx.valor:-tx.valor;return true},runAtomicFinancialMutation(fn,onError){const before=JSON.parse(JSON.stringify(context.S.data)),accountBefore=account;try{fn();return true}catch(e){context.S.data=before;account=accountBefore;onError?.(e);return false}}});
  context.Cards={applyTransferenciaEffect(t){if(t.kind==='rendimento_reserva'){reserve(t.origemId).valorAtual+=t.valor;return true}if(t.origemTipo==='conta')account-=t.valor;else{const b=reserve(t.origemId);if(!b||b.valorAtual+1e-9<t.valor)return false;b.valorAtual-=t.valor}if(t.destinoTipo==='conta')account+=t.valor;else{const b=reserve(t.destinoId);if(!b)return false;b.valorAtual+=t.valor}return true;}};
  vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(JS,'16-import-statement.js'),'utf8'),context);vm.runInContext(fs.readFileSync(path.join(JS,'16a-import-statement-images.js'),'utf8'),context);
  return {context,getAccount:()=>Math.round(account*100)/100,toasts};
}
function buildRows(context){const I=context.BorionImageImportInternals,lines=[];let y=10;const add=text=>{lines.push({text,normalized:text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),centerY:y,confidence:98});y+=12};add('Hoje');[
['17:33 Luz de vela','Pagamento','Movimento ...84EDQW -R$ 117,90'],['17:24 TERRA NOVA','Pix recebido','Movimento ...04YRVJ +R$ 150,00'],['08:57 Parcela YAS-62','Dinheiro reservado','Movimento ...PVY5T0 -R$ 3,36'],['08:56 Pessoal','Dinheiro retirado','Movimento ...75XC1S +R$ 3,27'],['08:56 Pessoal','Dinheiro reservado','Movimento ...ZR7XT0 -R$ 200,00'],['08:56 Borion 1','Dinheiro retirado','Movimento ...9597SF +R$ 100,05'],['08:55 Borion 2','Dinheiro retirado','Movimento ...8C3N8A +R$ 100,04']].forEach(t=>{t.forEach(add);y+=12});add('Disponível R$ 32,10');const c={referenceDate:'2026-07-17',referenceMonth:'2026-07',imageIndex:0,imageFingerprint:'fp',fileName:'ref.png',accountId:'mp',relativeDatesFound:false,detectedBalance:null};const rows=I.parseMercadoPagoImage({lines,text:lines.map(x=>x.text).join('\n'),confidence:98},c);return {I,rows,contextInfo:c,lines};}
function assert(condition,message){if(!condition)throw new Error(message)}
(function acceptance(){const {context,getAccount}=createContext();const {I,rows,contextInfo,lines}=buildRows(context);assert(rows.length===7,'Deveria reconhecer sete linhas');assert(contextInfo.detectedBalance===32.1,'Saldo lido deveria ser 32,10');I.mergeImageRows(rows);context.S.importState={mode:'image',images:[{name:'ref.png',fingerprint:'fp',rowsFound:7}],parsed:rows,selectedBank:'mp',detectedBank:'Mercado Pago',referenceDate:'2026-07-17',referenceMonth:'2026-07',stats:{}};I.commitImageStatementImport();const reserves=Object.fromEntries(context.S.data.reservas.boxes.map(b=>[b.nome,Math.round(b.valorAtual*100)/100]));assert(getAccount()===32.1,'Conta deveria variar 32,10');assert(context.S.data.transacoes.filter(t=>t.tipo==='receita').reduce((s,t)=>s+t.valor,0)===150,'Receita deveria ser 150');assert(context.S.data.transacoes.filter(t=>t.tipo==='variavel').reduce((s,t)=>s+t.valor,0)===117.9,'Despesa deveria ser 117,90');assert(reserves['Parcela YAS-62']===3.36,'YAS-62 incorreta');assert(reserves.Pessoal===196.73,'Pessoal incorreta');assert(reserves['Borion 1']===0&&reserves['Borion 2']===0,'Borion 1/2 incorretas');assert(context.S.data.transferencias.length===5,'Deveria haver cinco transferências');assert(context.S.data.importBatches.length===1,'Deveria haver um lote');const c2={referenceDate:'2026-07-17',referenceMonth:'2026-07',imageIndex:0,imageFingerprint:'fp2',fileName:'ref2.png',accountId:'mp',relativeDatesFound:false,detectedBalance:null};const rows2=I.parseMercadoPagoImage({lines,text:lines.map(x=>x.text).join('\n'),confidence:98},c2);I.mergeImageRows(rows2);assert(rows2.filter(r=>r.duplicateType==='existing').length===7,'Reimportação deveria detectar sete duplicadas');assert(rows2.filter(r=>r.incluir).length===0,'Duplicadas deveriam ficar desmarcadas');console.log('OK: parser, matemática, commit, reservas e reimportação.');})();
(function rollback(){const {context,getAccount}=createContext({failLast:true});const {I,rows}=buildRows(context);I.mergeImageRows(rows);context.S.importState={mode:'image',images:[{name:'ref.png',fingerprint:'fp',rowsFound:7}],parsed:rows,selectedBank:'mp',detectedBank:'Mercado Pago',referenceDate:'2026-07-17',referenceMonth:'2026-07',stats:{}};I.commitImageStatementImport();assert(getAccount()===0,'Rollback não restaurou Conta');assert(context.S.data.transacoes.length===0&&context.S.data.transferencias.length===0&&context.S.data.importBatches.length===0,'Rollback deixou registros parciais');console.log('OK: rollback atômico.');})();
