'use strict';
const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..');const read=f=>fs.readFileSync(path.join(root,f),'utf8');const assert=(c,m)=>{if(!c)throw new Error('FALHOU: '+m)};
const boot=read('js/14-events-boot-pwa.js'),index=read('index.html');
assert(boot.includes('const storageMode=getStorageMode()'),'modo de armazenamento deve ser lido antes dos serviços remotos');
assert(boot.includes("if(storageMode==='google_drive')")&&boot.includes('Promise.allSettled'),'tarefas independentes do boot Drive devem iniciar em paralelo');
assert(!/await\s+CloudStorage\.init\(\);/.test(boot),'CloudStorage.init não pode ser aguardado incondicionalmente');
assert(boot.includes("storageMode==='cloud'||storageMode==='supabase'||recovery"),'Supabase só pode inicializar no modo correspondente/recuperação');
assert(!index.includes('src="https://cdn.jsdelivr.net/npm/@supabase'),'index não pode carregar SDK Supabase sempre');
const localScripts=[...index.matchAll(/<script defer src="js\//g)].length;assert(localScripts>=30,'scripts locais devem usar defer preservando ordem');
assert(index.includes('rel="preload" href="css/styles.css?v=6.44.6"')&&index.includes('rel="preload" href="borion-emblem.png"'),'somente CSS/logo críticos devem ser preload');
console.log('OK: boot fast path lê o modo primeiro, paraleliza preparações e não inicializa Supabase no modo Drive/offline.');
