'use strict';
const fs=require('fs'),vm=require('vm'),path=require('path'),crypto=require('crypto').webcrypto;
const assert=(c,m)=>{if(!c)throw new Error('FALHOU: '+m)};
const context={console,crypto,TextEncoder};context.window=context;context.globalThis=context;vm.createContext(context);
vm.runInContext(fs.readFileSync(path.resolve(__dirname,'../js/01e-sync-core-v640.js'),'utf8'),context);
const Core=context.BorionSyncCore;
const rows=Array.from({length:600},(_,i)=>({id:'tx-'+i,nome:'Registro '+i,valor:i+0.25,data:'2026-07-21'}));
const base={profiles:[{id:'p1',name:'P1'},{id:'p2',name:'P2'}],config:{theme:'dark'},dataByProfile:{p1:{transacoes:rows},p2:{transacoes:[{id:'r1',valor:1}]}}};
const local=JSON.parse(JSON.stringify(base));local.dataByProfile.p1.transacoes[300].valor=999;
const remote=JSON.parse(JSON.stringify(base));remote.dataByProfile.p2.transacoes.push({id:'r2',valor:2});
const delta=Core.createAccountDelta(base,local);
assert(Core.accountDeltaHasChanges(delta),'mudança real deve gerar delta');
const fullBytes=Buffer.byteLength(JSON.stringify({basePayload:base,payload:local}));
const deltaBytes=Buffer.byteLength(JSON.stringify(delta));
assert(deltaBytes<fullBytes*0.7,'delta deve ser materialmente menor que duas cópias completas');
const merged=Core.mergeAccountDelta(delta,remote);
assert(merged.dataByProfile.p1.transacoes.find(x=>x.id==='tx-300').valor===999,'delta local deve ser aplicado');
assert(merged.dataByProfile.p2.transacoes.some(x=>x.id==='r2'),'mudança remota independente deve ser preservada');
assert(!Core.accountDeltaHasChanges(Core.createAccountDelta(base,base)),'snapshot idêntico não deve gerar operação');
console.log(`OK: journal delta preserva merge concorrente e reduziu ${fullBytes} bytes para ${deltaBytes} bytes.`);
